/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package clix.crud.create;

import clix.components.combobox.ComboBoxMultiSelection;
import clix.home.Home;
import clix.manager.FormsManager;
import clix.manager.SessionManager;
import clix.model.ModelReceta;
import clix.util.db;

import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author clint
 */
public class MainCrud2 extends javax.swing.JPanel {
        private ModelReceta receta;

        /**
         * Creates new form MainCrud2
         */
        public MainCrud2(ModelReceta receta) {
                this.receta = receta;
                initComponents();
                testData(comboBoxMultiSelection1);
                testData2(comboBoxMultiSelection2);
                // mostrar id de la receta
                System.out.println("id de la receta: " + receta.getId_receta());
                // mostrar receta completa
                System.out.println("receta: " + receta.toString());

                List<String> list = new ArrayList<>();
                /*
                 * list.add("Ajo");
                 * list.add("Cebolla");
                 */
                comboBoxMultiSelection1.setSelectedItems(list);

                btnRegresar.setBackground(new java.awt.Color(253, 83, 83));
                btnRegresar.setForeground(new java.awt.Color(245, 245, 245));
                btnRegresar.setRippleColor(new java.awt.Color(255, 255, 255));
                btnRegresar.setShadowColor(new java.awt.Color(253, 83, 83));

                guardarReceta.setBackground(new java.awt.Color(30, 180, 114));
                guardarReceta.setForeground(new java.awt.Color(245, 245, 245));
                guardarReceta.setRippleColor(new java.awt.Color(255, 255, 255));
                guardarReceta.setShadowColor(new java.awt.Color(30, 180, 114));

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                date = new clix.components.datechooser.DateChooser();
                jLabel1 = new javax.swing.JLabel();
                lblIngredieentes = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                lblComentario = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                textAreaComentario = new javax.swing.JTextArea();
                textAutor = new javax.swing.JTextField();
                comboBoxMultiSelection1 = new ComboBoxMultiSelection();
                guardarReceta = new clix.components.btn.Button();
                btnRegresar = new clix.components.btn.Button();
                txtDate = new javax.swing.JTextField();
                btnCalendar = new javax.swing.JButton();
                btnAhora = new javax.swing.JButton();
                lblComentario1 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                lblIngredieentes1 = new javax.swing.JLabel();
                comboBoxMultiSelection2 = new ComboBoxMultiSelection();
                jLabel2 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();

                date.setForeground(new java.awt.Color(93, 142, 204));
                date.setTextRefernce(txtDate);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
                jLabel1.setText("Termina de Crear tu Receta");

                lblIngredieentes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                lblIngredieentes.setText("Ingredientes");

                jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel3.setText("Nombre Autor");

                jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel4.setText("Comenta a tu receta");

                lblComentario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblComentario.setText("Comentario");

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                jLabel6.setText("Fecha");

                textAreaComentario.setColumns(20);
                textAreaComentario.setRows(5);
                jScrollPane1.setViewportView(textAreaComentario);

                guardarReceta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImg/minicohete.png"))); // NOI18N
                guardarReceta.setText("Gurdar receta");
                guardarReceta.addActionListener(this::guardarRecetaActionPerformed);

                btnRegresar.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/iconsImg/flecha-izquierda.png"))); // NOI18N
                btnRegresar.setText("regresar");
                btnRegresar.addActionListener(this::btnRegresarActionPerformed);

                txtDate.addActionListener(this::txtDateActionPerformed);

                btnCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImg/calen.png"))); // NOI18N
                btnCalendar.setText("calendario");
                btnCalendar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCalendarActionPerformed(evt);
                        }
                });

                btnAhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImg/today.png"))); // NOI18N
                btnAhora.setText("hoy");
                btnAhora.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAhoraActionPerformed(evt);
                        }
                });

                lblComentario1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
                lblComentario1.setText("¿Es tu favorito?");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));

                lblIngredieentes1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                lblIngredieentes1.setText("cantidad");

                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsImg/cohete.png"))); // NOI18N

                jLabel5.setText("\"rellenar secuencialmente: ingrediente y cantidad \"");

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
                jLabel7.setText("\"Estamos preparándonos para despegar 🚀\"");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(53, 53, 53)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lblIngredieentes1)
                                                                                                                                .addGap(56, 56, 56)
                                                                                                                                .addComponent(comboBoxMultiSelection2,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                565,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lblIngredieentes)
                                                                                                                                .addGap(31, 31, 31)
                                                                                                                                .addComponent(comboBoxMultiSelection1,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(167, 167, 167)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                330,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                455,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(181, 181,
                                                                                                                                                181)
                                                                                                                                .addComponent(btnAhora)
                                                                                                                                .addGap(22, 22, 22)
                                                                                                                                .addComponent(txtDate,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                111,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                .addGap(144, 144,
                                                                                                                                                                144)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addGap(70, 70, 70)))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(71, 71, 71)
                                                                                                                                                .addGroup(layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(lblComentario)
                                                                                                                                                                .addComponent(jScrollPane1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                315,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                .addComponent(lblComentario1)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGap(70, 70, 70)
                                                                                                                                .addGroup(layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(textAutor,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                316,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(btnCalendar)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                140,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                                .addGap(133, 133, 133))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(240, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addGap(363, 363,
                                                                                                                                363))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel7,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                235,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addComponent(btnRegresar,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                108,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(58, 58, 58)
                                                                                                                .addComponent(guardarReceta,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                163,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(429, 429,
                                                                                                                                429)))));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(jLabel1)
                                                                .addGap(70, 70, 70)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel4)
                                                                                                .addGap(24, 24, 24)
                                                                                                .addComponent(jLabel3)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(textAutor,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(28, 28, 28)
                                                                                                .addComponent(jLabel6)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(txtDate,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(btnCalendar)
                                                                                                                .addComponent(btnAhora))
                                                                                                .addGap(41, 41, 41)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblComentario1)
                                                                                                                .addComponent(jComboBox1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(36, 36, 36)
                                                                                                .addComponent(lblComentario)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                61,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(guardarReceta,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(btnRegresar,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(16, 16, 16))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lblIngredieentes)
                                                                                                                .addComponent(comboBoxMultiSelection1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblIngredieentes1)
                                                                                                                .addComponent(comboBoxMultiSelection2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                30,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(4, 4, 4)
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                268,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel7)
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))));
        }// </editor-fold>//GEN-END:initComponents

        private void testData(JComboBox<String> combo) {
                combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                                "Ajo",
                                "Cebolla",
                                "Tomate",
                                "Zanahoria",
                                "Pimiento",
                                "Pepino",
                                "Lechuga",
                                "Espinaca",
                                "Papa",
                                "Batata",
                                "Calabaza",
                                "Brócoli",
                                "Coliflor",
                                "Apio",
                                "Espárragos",
                                "Champiñones",
                                "Maíz",
                                "Guisantes",
                                "Frijoles",
                                "Lentejas",
                                "Arroz",
                                "Quinoa",
                                "Trigo",
                                "Harina",
                                "Maicena",
                                "Azúcar",
                                "Sal",
                                "Pimienta",
                                "Vinagre",
                                "Aceite",
                                "Mantequilla",
                                "Leche",
                                "Huevos",
                                "Harina de trigo",
                                "Levadura",
                                "Canela",
                                "Nuez Moscada",
                                "Jengibre",
                                "Cúrcuma",
                                "Comino",
                                "Orégano",
                                "Perejil",
                                "Albahaca",
                                "Cilantro",
                                "Miel",
                                "Mostaza",
                                "Salsa de soja",
                                "Salsa Worcestershire",
                                "Salsa de tomate",
                                "Salsa de chile",
                                "Caldo de pollo",
                                "Caldo de verduras"
                }));

        }

        private void testData2(JComboBox<String> combo) {
                combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                                "100 gramos",
                                "200 gramos",
                                "300 gramos",
                                "400 gramos",
                                "500 gramos",
                                "1 kilo",
                                "2 kilos",
                                "3 kilos",
                                "4 kilos",
                                "5 kilos",
                                "1 litro",
                                "2 litros",
                                "3 litros",
                                "4 litros",
                                "5 litros",
                                "10 mililitros",
                                "20 mililitros",
                                "30 mililitros",
                                "40 mililitros",
                                "50 mililitros",
                                "1 cucharada",
                                "2 cucharadas",
                                "3 cucharadas",
                                "4 cucharadas",
                                "5 cucharadas",
                                "1 cucharadita",
                                "2 cucharaditas",
                                "3 cucharaditas",
                                "1 taza",
                                "2 tazas",
                                "3 tazas",
                                "4 tazas",
                                "5 tazas",
                                "1 unidad",
                                "2 unidades",
                                "3 unidades",
                                "4 unidades",
                                "5 unidades",
                                "6 unidades",
                }));

        }

        private void guardarRecetaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_guardarRecetaActionPerformed

                List<String> ingredientes = new ArrayList<>(comboBoxMultiSelection1.getSelectedItems());
                List<String> cantidades = new ArrayList<>(comboBoxMultiSelection2.getSelectedItems());

                String autor = textAutor.getText();
                String fecha = txtDate.getText();
                String comentario = textAreaComentario.getText();
                // hace rque favorito sea un booleano
                String favoritoText = Objects.requireNonNull(jComboBox1.getSelectedItem()).toString();
                // tru si es si y false si es no
                boolean favorito = favoritoText.equals("si");

                if (ingredientes.isEmpty() || cantidades.isEmpty() || autor.isEmpty() || fecha.isEmpty()
                                || comentario.isEmpty()
                                || favoritoText.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos");
                } else {
                        try {
                                for (int i = 0; i < ingredientes.size(); i++) {
                                        String ingrediente = ingredientes.get(i);
                                        String cantidad = cantidades.get(i);

                                        String sql = "INSERT INTO Ingrediente (nombre, medida) VALUES (?, ?) RETURNING id_ingrediente";
                                        try (PreparedStatement pst = db.getConnection().prepareStatement(sql)) {
                                                pst.setString(1, ingrediente);
                                                pst.setString(2, cantidad);
                                                try (ResultSet rs = pst.executeQuery()) {
                                                        if (rs.next()) {
                                                                int id_ingrediente = rs.getInt(1);

                                                                sql = "INSERT INTO Ingrediente_receta (id_receta, id_ingrediente) VALUES (?, ?)";
                                                                try (PreparedStatement pst2 = db.getConnection()
                                                                                .prepareStatement(sql)) {
                                                                        pst2.setInt(1, receta.getId_receta());
                                                                        pst2.setInt(2, id_ingrediente);
                                                                        pst2.executeUpdate();
                                                                }
                                                        }
                                                }
                                        }
                                }


                                String sqlB = "INSERT INTO Comentarios (id_receta, nombre_autor, fecha, comentario) VALUES (?, ?, ?, ?)";
                                try (PreparedStatement pst = db.getConnection().prepareStatement(sqlB)) {
                                        pst.setInt(1, receta.getId_receta());
                                        pst.setString(2, autor);

                                        DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                                        DateTimeFormatter outputFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                                        LocalDate parsedDate = LocalDate.parse(fecha, inputFormatter);
                                        String formattedDate = outputFormatter.format(parsedDate);
                                        pst.setDate(3, java.sql.Date.valueOf(formattedDate));

                                        pst.setString(4, comentario);
                                        pst.executeUpdate();
                                } catch (Exception ex) {
                                        System.out.println(ex);
                                }

                                String sqlC = "INSERT INTO Favorito (favorito, id_usuario, id_receta) VALUES (?, ?, ?)";
                                try (PreparedStatement pst = db.getConnection().prepareStatement(sqlC)) {
                                        pst.setBoolean(1, favorito);
                                        pst.setInt(2, SessionManager.getInstance().getUserId());
                                        pst.setInt(3, receta.getId_receta());
                                        pst.executeUpdate();
                                } catch (Exception ex) {
                                        System.out.println(ex);
                                }

                                JOptionPane.showMessageDialog(null, "Receta guardada con éxito");

                                FormsManager.getInstance().showForm(new Home());
                        } catch (Exception ex) {
                                System.out.println(ex);
                        }
                }

        }// GEN-LAST:event_guardarRecetaActionPerformed

        private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegresarActionPerformed
                FormsManager.getInstance().showForm(new MainCrud());
        }// GEN-LAST:event_btnRegresarActionPerformed

        private void btnAhoraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAhoraActionPerformed
                date.toDay();
        }// GEN-LAST:event_btnAhoraActionPerformed

        private void btnCalendarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalendarActionPerformed
                date.showPopup();
        }// GEN-LAST:event_btnCalendarActionPerformed

        private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDateActionPerformed

        }// GEN-LAST:event_txtDateActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAhora;
        private javax.swing.JButton btnCalendar;
        private clix.components.btn.Button btnRegresar;
        private ComboBoxMultiSelection comboBoxMultiSelection1;
        private ComboBoxMultiSelection comboBoxMultiSelection2;
        private clix.components.datechooser.DateChooser date;
        private clix.components.btn.Button guardarReceta;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblComentario;
        private javax.swing.JLabel lblComentario1;
        private javax.swing.JLabel lblIngredieentes;
        private javax.swing.JLabel lblIngredieentes1;
        private javax.swing.JTextArea textAreaComentario;
        private javax.swing.JTextField textAutor;
        private javax.swing.JTextField txtDate;
        // End of variables declaration//GEN-END:variables

}
