package clix.model;

import java.util.Date;

public class Comentarios {
    /*
    * CREATE TABLE IF NOT EXISTS Comentarios (
  id_comentarios INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_receta INT,
  nombre_autor VARCHAR(255),
  fecha DATE,
  comentario TEXT
);
    * */
    int id_comentarios;
    int id_receta;
    String nombre_autor;
    Date fecha;
    String comentario;

public Comentarios() {
    }

    public Comentarios(int id_comentarios, int id_receta, String nombre_autor, Date fecha, String comentario) {
        this.id_comentarios = id_comentarios;
        this.id_receta = id_receta;
        this.nombre_autor = nombre_autor;
        this.fecha = fecha;
        this.comentario = comentario;
    }

    public Comentarios(String nombreAutor, Date date2, String comentario) {
        this.nombre_autor = nombreAutor;
        this.fecha = date2;
        this.comentario = comentario;
    }


    public int getId_comentarios() {
        return id_comentarios;
    }

    public void setId_comentarios(int id_comentarios) {
        this.id_comentarios = id_comentarios;
    }

    public int getId_receta() {
        return id_receta;
    }

    public void setId_receta(int id_receta) {
        this.id_receta = id_receta;
    }

    public String getNombre_autor() {
        return nombre_autor;
    }

    public void setNombre_autor(String nombre_autor) {
        this.nombre_autor = nombre_autor;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
}

