package clix.model;

public class Usuario {
    /*
    * CREATE TABLE IF NOT EXISTS Usuario (
  id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255),
  contrasena VARCHAR(255),
  correo_electronico VARCHAR(255)
);
    * */
    int id_usuario;
    String nombre;
    String contrasena;

    public Usuario() {
    }

    public Usuario(int id_usuario, String nombre, String contrasena) {
        this.id_usuario = id_usuario;
        this.nombre = nombre;
        this.contrasena = contrasena;
    }

    public int getId_usuario() {
        return id_usuario;
    }

    public void setId_usuario(int id_usuario) {
        this.id_usuario = id_usuario;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getContrasena() {
        return contrasena;
    }

    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
}

